package binance

const (
	EndpointPing               = "/api/v3/ping"
	EndpointTime               = "/api/v3/time"
	EndpointExchangeInfo       = "/api/v3/exchangeInfo"
	EndpointDepth              = "/api/v3/depth"
	EndpointTrades             = "/api/v3/trades"
	EndpointHistoricalTrades   = "/api/v3/historicalTrades"
	EndpointAggTrades          = "/api/v3/aggTrades"
	EndpointKlines             = "/api/v3/klines"
	EndpointAvgPrice           = "/api/v3/avgPrice"
	EndpointTicker24h          = "/api/v3/ticker/24hr"
	EndpointTickerPrice        = "/api/v3/ticker/price"
	EndpointTickerBook         = "/api/v3/ticker/bookTicker"
	EndpointOrder              = "/api/v3/order"
	EndpointOrderTest          = "/api/v3/order/test"
	EndpointOpenOrders         = "/api/v3/openOrders"
	EndpointCancelReplaceOrder = "/api/v3/order/cancelReplace"
	EndpointOrdersAll          = "/api/v3/allOrders"
	EndpointAccount            = "/api/v3/account"
	EndpointAccountTrades      = "/api/v3/myTrades"
	EndpointRateLimit          = "/api/v3/rateLimit/order"
	EndpointDataStream         = "/api/v3/userDataStream"
)
